apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: first-nginx
  labels:
    app: nginx
    release: first-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      release: first-nginx
  template:
    metadata:
      labels:
        app: nginx
        release: first-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: second-nginx
  labels:
    app: nginx
    release: second-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      release: second-nginx
  template:
    metadata:
      labels:
        app: nginx
        release: second-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
